// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfclEJxN6D635ety9q-jYhB9DwR51Vrrg',
    appId: '1:395601992434:web:3cfe3e991e5c046ec5ce6b',
    messagingSenderId: '395601992434',
    projectId: 'pgerd-project',
    authDomain: 'pgerd-project.firebaseapp.com',
    storageBucket: 'pgerd-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJB0XW1BrbS01UFTEVhDtIq23dbe0W2c',
    appId: '1:395601992434:android:95a9b110318787c3c5ce6b',
    messagingSenderId: '395601992434',
    projectId: 'pgerd-project',
    storageBucket: 'pgerd-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_4w08kRix5cwhWg56WHqAKaSpmMWvmMI',
    appId: '1:395601992434:ios:abeeefa2255c984ec5ce6b',
    messagingSenderId: '395601992434',
    projectId: 'pgerd-project',
    storageBucket: 'pgerd-project.firebasestorage.app',
    androidClientId:
        '395601992434-n2vkgjecpisn31cfufmko2bofisfcp56.apps.googleusercontent.com',
    iosClientId:
        '395601992434-2ol73gecnprsi0t0j0oobtgsvj594tni.apps.googleusercontent.com',
    iosBundleId: 'com.example.pabTugasBesar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_4w08kRix5cwhWg56WHqAKaSpmMWvmMI',
    appId: '1:395601992434:ios:abeeefa2255c984ec5ce6b',
    messagingSenderId: '395601992434',
    projectId: 'pgerd-project',
    storageBucket: 'pgerd-project.firebasestorage.app',
    androidClientId:
        '395601992434-n2vkgjecpisn31cfufmko2bofisfcp56.apps.googleusercontent.com',
    iosClientId:
        '395601992434-2ol73gecnprsi0t0j0oobtgsvj594tni.apps.googleusercontent.com',
    iosBundleId: 'com.example.pabTugasBesar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfclEJxN6D635ety9q-jYhB9DwR51Vrrg',
    appId: '1:395601992434:web:184fb7d1dee6e8dcc5ce6b',
    messagingSenderId: '395601992434',
    projectId: 'pgerd-project',
    authDomain: 'pgerd-project.firebaseapp.com',
    storageBucket: 'pgerd-project.firebasestorage.app',
  );
}
